2018-10-05 21:47:49 ERROR ConnectionUtil:95 - Couldn't retrieve all accounts
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1521:xe
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.repository.BankRepositoryJdbc.findAllAccounts(BankRepositoryJdbc.java:66)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:131)
2018-10-05 22:02:26 ERROR ConnectionUtil:95 - Couldn't retrieve all accounts
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1521:xe
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.repository.BankRepositoryJdbc.findAllAccounts(BankRepositoryJdbc.java:68)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:131)
2018-10-05 22:09:50 ERROR ConnectionUtil:95 - Couldn't retrieve all accounts
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1521:xe
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.repository.BankRepositoryJdbc.findAllAccounts(BankRepositoryJdbc.java:68)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:131)
2018-10-05 22:29:18 ERROR ConnectionUtil:41 - Couldn't insert account
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1521:xe
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:22)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:21)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-05 22:29:18 ERROR ConnectionUtil:41 - Couldn't insert account
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1521:xe
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:22)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:21)
	at com.revature.test.AccountRegistrationTest.registrationSuccess(AccountRegistrationTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-05 22:29:32 ERROR ConnectionUtil:41 - Couldn't insert account
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1521:xe
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:22)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:21)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-05 22:29:32 ERROR ConnectionUtil:41 - Couldn't insert account
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1521:xe
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:22)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:21)
	at com.revature.test.AccountRegistrationTest.registrationSuccess(AccountRegistrationTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-05 22:29:42 ERROR ConnectionUtil:41 - Couldn't insert account
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1521:xe
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:22)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:21)
	at com.revature.test.AccountRegistrationTest.registrationSuccess(AccountRegistrationTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-05 22:30:01 ERROR ConnectionUtil:41 - Couldn't insert account
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1521:xe
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:22)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:21)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-05 22:34:00 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1521:xe
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
2018-10-05 22:35:09 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1521:xe
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
2018-10-05 22:36:39 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1521:xe
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
2018-10-05 22:45:19 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:272)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:263)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1360)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:486)
	... 8 more
2018-10-05 22:45:32 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:272)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:263)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1360)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:486)
	... 8 more
2018-10-05 22:46:02 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:272)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:263)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1360)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:486)
	... 8 more
2018-10-05 22:48:24 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:272)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:263)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1360)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:486)
	... 8 more
2018-10-05 22:50:06 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:272)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:263)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1360)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:486)
	... 8 more
2018-10-05 22:52:12 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:272)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:263)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1360)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:486)
	... 8 more
2018-10-05 22:53:22 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLRecoverableException: Listener refused the connection with the following error:
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor
 
	at oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:272)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:263)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1360)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:486)
	... 8 more
2018-10-05 22:54:32 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:272)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:263)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1360)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:486)
	... 8 more
2018-10-05 22:56:16 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:272)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:263)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1360)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:486)
	... 8 more
2018-10-05 22:56:57 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:272)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:263)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1360)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:486)
	... 8 more
2018-10-05 23:03:19 ERROR ConnectionUtil:31 - Couldn't establish connection
java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:18)
	at com.revature.util.ConnectionUtil.main(ConnectionUtil.java:26)
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
	at oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:272)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:263)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1360)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:486)
	... 8 more
2018-10-05 23:15:36 ERROR ConnectionUtil:41 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("BANK_DB"."ACCOUNT"."A_ACCOUNT_TYPE")

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:36)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:21)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-05 23:19:02 ERROR ConnectionUtil:41 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("BANK_DB"."ACCOUNT"."A_ACCOUNT_TYPE")

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:36)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:21)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-05 23:19:02 ERROR ConnectionUtil:41 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-02290: check constraint (BANK_DB.CHK_ACCT_STATUS) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:36)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:21)
	at com.revature.test.AccountRegistrationTest.registrationSuccess(AccountRegistrationTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-05 23:19:56 ERROR ConnectionUtil:41 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-02290: check constraint (BANK_DB.CHK_ACCT_STATUS) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:36)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:21)
	at com.revature.test.AccountRegistrationTest.registrationSuccess(AccountRegistrationTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-05 23:20:20 ERROR ConnectionUtil:41 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("BANK_DB"."ACCOUNT"."A_ACCOUNT_TYPE")

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:36)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:21)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-05 23:27:36 ERROR ConnectionUtil:41 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("BANK_DB"."ACCOUNT"."A_ACCOUNT_TYPE")

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:36)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:21)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-06 16:30:00 INFO  ConnectionUtil:168 - [Account [accountNumber=10, accountType=CUSTODIAL, accountStatus=INACTIVE, accountBalance=25.0, accountHash=FD2371284C67F0ACE38265D77BD746D5, customer=Customer [id=2356, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=12345, accountType=CHECKING, accountStatus=ACTIVE, accountBalance=100.0, accountHash=E9DED1D83F9312BD1555995B6DB377AE, customer=Customer [id=1, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=12, accountType=CUSTODIAL, accountStatus=INACTIVE, accountBalance=25.0, accountHash=FD2371284C67F0ACE38265D77BD746D5, customer=Customer [id=2356, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=2, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=5000.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=666, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=8, accountType=SAVINGS, accountStatus=INACTIVE, accountBalance=5025.0, accountHash=7818B2C5EEC41EF1065FE40A88FC433E, customer=Customer [id=2356, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=9, accountType=SAVINGS, accountStatus=INACTIVE, accountBalance=5025.0, accountHash=7818B2C5EEC41EF1065FE40A88FC433E, customer=Customer [id=2356, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=3, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=5000.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=666, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]]]
2018-10-06 16:35:01 INFO  ConnectionUtil:141 - No customers to display
2018-10-06 16:35:01 INFO  ConnectionUtil:169 - 
2018-10-06 16:37:28 ERROR ConnectionUtil:44 - Couldn't insert account
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:39)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:23)
	at com.revature.test.AccountRegistrationTest.registrationSuccess(AccountRegistrationTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-06 16:38:26 ERROR ConnectionUtil:44 - Couldn't insert account
java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:39)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:23)
	at com.revature.test.AccountRegistrationTest.registrationSuccess(AccountRegistrationTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-06 16:39:56 INFO  ConnectionUtil:168 - [Account [accountNumber=13, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=420.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=421, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=10, accountType=CUSTODIAL, accountStatus=INACTIVE, accountBalance=25.0, accountHash=FD2371284C67F0ACE38265D77BD746D5, customer=Customer [id=2356, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=12345, accountType=CHECKING, accountStatus=ACTIVE, accountBalance=100.0, accountHash=E9DED1D83F9312BD1555995B6DB377AE, customer=Customer [id=1, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=12, accountType=CUSTODIAL, accountStatus=INACTIVE, accountBalance=25.0, accountHash=FD2371284C67F0ACE38265D77BD746D5, customer=Customer [id=2356, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=2, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=5000.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=666, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=8, accountType=SAVINGS, accountStatus=INACTIVE, accountBalance=5025.0, accountHash=7818B2C5EEC41EF1065FE40A88FC433E, customer=Customer [id=2356, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=9, accountType=SAVINGS, accountStatus=INACTIVE, accountBalance=5025.0, accountHash=7818B2C5EEC41EF1065FE40A88FC433E, customer=Customer [id=2356, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=3, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=5000.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=666, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]]]
2018-10-06 16:48:07 INFO  ConnectionUtil:170 - [Account [accountNumber=13, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=420.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=421, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=10, accountType=CUSTODIAL, accountStatus=INACTIVE, accountBalance=25.0, accountHash=FD2371284C67F0ACE38265D77BD746D5, customer=Customer [id=2356, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=12345, accountType=CHECKING, accountStatus=ACTIVE, accountBalance=100.0, accountHash=E9DED1D83F9312BD1555995B6DB377AE, customer=Customer [id=1, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=12, accountType=CUSTODIAL, accountStatus=INACTIVE, accountBalance=25.0, accountHash=FD2371284C67F0ACE38265D77BD746D5, customer=Customer [id=2356, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=2, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=5000.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=666, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=8, accountType=SAVINGS, accountStatus=INACTIVE, accountBalance=5025.0, accountHash=7818B2C5EEC41EF1065FE40A88FC433E, customer=Customer [id=2356, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=9, accountType=SAVINGS, accountStatus=INACTIVE, accountBalance=5025.0, accountHash=7818B2C5EEC41EF1065FE40A88FC433E, customer=Customer [id=2356, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]], Account [accountNumber=3, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=5000.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=666, firstName=null, lastName=null, emailAddress=null, loginName=null, account=null]]]
2018-10-06 16:48:31 INFO  ConnectionUtil:82 - No accounts to display
2018-10-06 16:48:31 INFO  ConnectionUtil:170 - 
2018-10-06 16:49:24 INFO  ConnectionUtil:82 - No accounts to display
2018-10-06 16:49:24 INFO  ConnectionUtil:170 - 
2018-10-06 16:49:24 INFO  ConnectionUtil:143 - No customers to display
2018-10-06 16:49:24 INFO  ConnectionUtil:171 - 
2018-10-06 20:50:40 ERROR ConnectionUtil:44 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("BANK_DB"."ACCOUNT"."A_ACCOUNT_TYPE")

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:39)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:23)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-06 20:52:15 ERROR ConnectionUtil:44 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("BANK_DB"."ACCOUNT"."A_ACCOUNT_TYPE")

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:39)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:23)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-06 20:56:50 ERROR ConnectionUtil:44 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("BANK_DB"."ACCOUNT"."A_ACCOUNT_TYPE")

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:39)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:23)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-06 21:06:27 ERROR ConnectionUtil:44 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("BANK_DB"."ACCOUNT"."A_ACCOUNT_TYPE")

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:39)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:23)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 10:39:11 INFO  BankService:52 - In register Customer
2018-10-08 10:40:22 INFO  BankService:52 - In register Customer
2018-10-08 10:40:22 ERROR ConnectionUtil:130 - Couldn't insert customer
java.sql.SQLSyntaxErrorException: ORA-00913: too many values

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:125)
	at com.revature.service.BankServiceImpl.registerCustomer(BankServiceImpl.java:53)
	at com.revature.test.AccountRegistrationTest.registrationSuccessCustomer(AccountRegistrationTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 10:41:07 INFO  BankService:52 - In register Customer
2018-10-08 10:41:08 ERROR ConnectionUtil:130 - Couldn't insert customer
java.sql.SQLSyntaxErrorException: ORA-00913: too many values

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:125)
	at com.revature.service.BankServiceImpl.registerCustomer(BankServiceImpl.java:53)
	at com.revature.test.AccountRegistrationTest.registrationSuccessCustomer(AccountRegistrationTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 11:22:12 INFO  BankService:23 - In register Account
2018-10-08 11:23:02 INFO  BankService:23 - In register Account
2018-10-08 11:23:03 ERROR ConnectionUtil:44 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("BANK_DB"."ACCOUNT"."A_ACCOUNT_TYPE")

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:39)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:24)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 11:23:03 INFO  BankService:23 - In register Account
2018-10-08 11:23:42 INFO  BankService:52 - In register Customer
2018-10-08 11:23:43 ERROR ConnectionUtil:130 - Couldn't insert customer
java.sql.SQLSyntaxErrorException: ORA-01722: invalid number

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:125)
	at com.revature.service.BankServiceImpl.registerCustomer(BankServiceImpl.java:53)
	at com.revature.test.AccountRegistrationTest.registrationSuccessCustomer(AccountRegistrationTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 11:25:07 INFO  BankService:52 - In register Customer
2018-10-08 11:27:20 INFO  BankService:52 - In register Customer
2018-10-08 11:35:50 INFO  BankService:23 - In register Account
2018-10-08 11:35:51 INFO  BankService:52 - In register Customer
2018-10-08 11:35:51 INFO  BankService:23 - In register Account
2018-10-08 11:41:46 INFO  BankService:52 - In register Customer
2018-10-08 11:43:20 INFO  BankService:52 - In register Customer
2018-10-08 11:45:33 INFO  BankService:52 - In register Customer
2018-10-08 11:45:33 INFO  ConnectionUtil:110 - In bank repository
2018-10-08 11:50:38 INFO  BankService:52 - In register Customer
2018-10-08 11:50:38 INFO  ConnectionUtil:110 - In bank repository
2018-10-08 11:50:39 ERROR ConnectionUtil:133 - Couldn't insert customer
java.sql.SQLIntegrityConstraintViolationException: ORA-02291: integrity constraint (BANK_DB.FK_CUSTOMER_ACCOUNT) violated - parent key not found

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:127)
	at com.revature.service.BankServiceImpl.registerCustomer(BankServiceImpl.java:53)
	at com.revature.test.AccountRegistrationTest.registrationSuccessCustomer(AccountRegistrationTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 11:50:39 INFO  BankService:55 - Invalid customer (logger)
2018-10-08 12:25:29 INFO  BankService:52 - In register Customer
2018-10-08 12:25:29 INFO  ConnectionUtil:110 - In bank repository
2018-10-08 12:25:30 ERROR ConnectionUtil:133 - Couldn't insert customer
java.sql.SQLIntegrityConstraintViolationException: ORA-02291: integrity constraint (BANK_DB.FK_CUSTOMER_ACCOUNT) violated - parent key not found

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:127)
	at com.revature.service.BankServiceImpl.registerCustomer(BankServiceImpl.java:53)
	at com.revature.test.AccountRegistrationTest.registrationSuccessCustomer(AccountRegistrationTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 12:25:30 INFO  BankService:55 - Invalid customer (logger)
2018-10-08 12:26:14 INFO  BankService:52 - In register Customer
2018-10-08 12:26:14 INFO  ConnectionUtil:110 - In bank repository
2018-10-08 12:26:15 ERROR ConnectionUtil:133 - Couldn't insert customer
java.sql.SQLIntegrityConstraintViolationException: ORA-02291: integrity constraint (BANK_DB.FK_CUSTOMER_ACCOUNT) violated - parent key not found

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:127)
	at com.revature.service.BankServiceImpl.registerCustomer(BankServiceImpl.java:53)
	at com.revature.test.AccountRegistrationTest.registrationSuccessCustomer(AccountRegistrationTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 12:26:15 INFO  BankService:55 - Invalid customer (logger)
2018-10-08 12:26:40 INFO  BankService:52 - In register Customer
2018-10-08 12:26:40 INFO  ConnectionUtil:110 - In bank repository
2018-10-08 12:27:50 INFO  BankService:52 - In register Customer
2018-10-08 12:27:50 INFO  ConnectionUtil:110 - In bank repository
2018-10-08 12:27:51 INFO  ConnectionUtil:128 - statement.executeUpdate > 0
2018-10-08 12:42:01 INFO  ConnectionUtil:240 - [Account [accountNumber=41, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=0.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=1, firstName=null, lastName=null, loginName=null, account=null, customerHash=null, emailAddress=null]], Account [accountNumber=43, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=0.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=1, firstName=null, lastName=null, loginName=null, account=null, customerHash=null, emailAddress=null]]]
2018-10-08 12:53:35 INFO  ConnectionUtil:236 - [Customer [id=null, firstName=Jane, lastName=Doe, loginName=testlogin2, account=Account [accountNumber=41, accountType=null, accountStatus=null, accountBalance=0.0, accountHash=null, customer=null], customerHash=null, emailAddress=jane@email], Customer [id=null, firstName=John, lastName=Doe, loginName=TestLogin1, account=Account [accountNumber=0, accountType=null, accountStatus=null, accountBalance=0.0, accountHash=null, customer=null], customerHash=null, emailAddress=TEST@EMAIL]]
2018-10-08 12:55:09 INFO  ConnectionUtil:235 - [Account [accountNumber=43, accountType=null, accountStatus=null, accountBalance=0.0, accountHash=null, customer=null], Account [accountNumber=41, accountType=null, accountStatus=null, accountBalance=0.0, accountHash=null, customer=null]]
2018-10-08 12:56:25 INFO  ConnectionUtil:235 - [Account [accountNumber=41, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=0.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=1, firstName=null, lastName=null, loginName=null, account=null, customerHash=null, emailAddress=null]], Account [accountNumber=43, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=0.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=1, firstName=null, lastName=null, loginName=null, account=null, customerHash=null, emailAddress=null]]]
2018-10-08 13:11:33 ERROR ConnectionUtil:93 - Couldn't retrieve all accounts
java.sql.SQLException: Invalid column name
	at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3965)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.findColumn(InsensitiveScrollableResultSet.java:299)
	at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:1460)
	at com.revature.repository.BankRepositoryJdbc.findAllAccounts(BankRepositoryJdbc.java:75)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:239)
2018-10-08 13:11:33 INFO  ConnectionUtil:239 - 
2018-10-08 13:14:25 INFO  ConnectionUtil:234 - [Account [accountNumber=41, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=0.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=1, firstName=null, lastName=null, loginName=null, account=null, customerHash=null, emailAddress=null]], Account [accountNumber=43, accountType=SAVINGS, accountStatus=ACTIVE, accountBalance=0.0, accountHash=5E3DF3F6EEA673EA57FD221938A886C7, customer=Customer [id=1, firstName=null, lastName=null, loginName=null, account=null, customerHash=null, emailAddress=null]]]
2018-10-08 13:29:13 ERROR ConnectionUtil:213 - Couldn't retrieve login names
java.sql.SQLSyntaxErrorException: ORA-00904: "LOGIN_NAME": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:776)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:897)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1034)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3867)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1502)
	at com.revature.repository.BankRepositoryJdbc.findByLoginName(BankRepositoryJdbc.java:195)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:258)
2018-10-08 13:29:13 INFO  ConnectionUtil:258 - 
2018-10-08 13:31:35 INFO  ConnectionUtil:258 - [Customer [id=null, firstName=null, lastName=null, loginName=testlogin2, account=null, customerHash=null, emailAddress=null], Customer [id=null, firstName=null, lastName=null, loginName=TestLogin1, account=null, customerHash=null, emailAddress=null]]
2018-10-08 13:33:16 INFO  ConnectionUtil:258 - [Customer [id=null, firstName=null, lastName=null, loginName=testlogin2, account=null, customerHash=null, emailAddress=null], Customer [id=null, firstName=null, lastName=null, loginName=TestLogin1, account=null, customerHash=null, emailAddress=null]]
2018-10-08 13:34:50 ERROR ConnectionUtil:215 - Couldn't retrieve login names
java.sql.SQLException: Result set after last row
	at oracle.jdbc.driver.GeneratedScrollableResultSet.getString(GeneratedScrollableResultSet.java:879)
	at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:1460)
	at com.revature.repository.BankRepositoryJdbc.findByLoginName(BankRepositoryJdbc.java:204)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:260)
2018-10-08 13:34:50 INFO  ConnectionUtil:260 - 
2018-10-08 13:35:09 INFO  ConnectionUtil:261 - [Customer [id=null, firstName=null, lastName=null, loginName=testlogin2, account=null, customerHash=null, emailAddress=null], Customer [id=null, firstName=null, lastName=null, loginName=TestLogin1, account=null, customerHash=null, emailAddress=null]]
2018-10-08 13:38:07 INFO  ConnectionUtil:266 - 
2018-10-08 13:39:00 INFO  ConnectionUtil:264 - [Customer [id=null, firstName=null, lastName=null, loginName=testlogin2, account=null, customerHash=null, emailAddress=null], Customer [id=null, firstName=null, lastName=null, loginName=TestLogin1, account=null, customerHash=null, emailAddress=null]]
2018-10-08 13:41:40 INFO  ConnectionUtil:265 - TestLogin1
2018-10-08 13:44:44 INFO  ConnectionUtil:217 - NOT A VALID LOGIN NAME
2018-10-08 13:44:44 INFO  ConnectionUtil:271 - 
2018-10-08 13:45:36 INFO  ConnectionUtil:217 - NOT A VALID LOGIN NAME
2018-10-08 13:45:36 INFO  ConnectionUtil:272 - 
2018-10-08 13:46:00 INFO  ConnectionUtil:221 - Your login name testlogin2 has been found!
2018-10-08 13:46:00 INFO  ConnectionUtil:272 - testlogin2
2018-10-08 13:48:13 INFO  ConnectionUtil:221 - Your login name testlogin2 has been found!
2018-10-08 13:48:13 INFO  ConnectionUtil:272 - testlogin2
2018-10-08 13:48:20 INFO  ConnectionUtil:221 - Your login name testlogin2 has been found!
2018-10-08 13:48:20 INFO  ConnectionUtil:272 - testlogin2
2018-10-08 13:49:29 INFO  ConnectionUtil:221 - NOT A VALID LOGIN NAME
2018-10-08 13:49:29 INFO  ConnectionUtil:273 - 
2018-10-08 13:49:42 INFO  ConnectionUtil:221 - NOT A VALID LOGIN NAME
2018-10-08 13:49:42 INFO  ConnectionUtil:273 - 
2018-10-08 13:50:11 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:50:11 INFO  ConnectionUtil:274 - 
2018-10-08 13:51:09 INFO  ConnectionUtil:205 - TestLogin1
2018-10-08 13:51:09 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:51:09 INFO  ConnectionUtil:274 - 
2018-10-08 13:51:33 INFO  ConnectionUtil:205 - TestLogin1
2018-10-08 13:51:33 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:51:33 INFO  ConnectionUtil:205 - testlogin2
2018-10-08 13:51:33 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:51:33 INFO  ConnectionUtil:272 - 
2018-10-08 13:52:01 INFO  ConnectionUtil:205 - TestLogin1
2018-10-08 13:52:01 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:52:01 INFO  ConnectionUtil:205 - testlogin2
2018-10-08 13:52:01 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:52:02 INFO  ConnectionUtil:272 - testlogin2
2018-10-08 13:52:30 INFO  ConnectionUtil:205 - TestLogin1
2018-10-08 13:52:30 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:52:30 INFO  ConnectionUtil:205 - testlogin2
2018-10-08 13:52:30 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:52:30 INFO  ConnectionUtil:273 - 
2018-10-08 13:52:50 INFO  ConnectionUtil:205 - TestLogin1
2018-10-08 13:52:50 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:52:50 INFO  ConnectionUtil:205 - testlogin2
2018-10-08 13:52:50 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:52:50 INFO  ConnectionUtil:273 - 
2018-10-08 13:53:11 INFO  ConnectionUtil:205 - TestLogin1
2018-10-08 13:53:11 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:53:11 INFO  ConnectionUtil:205 - testlogin2
2018-10-08 13:53:11 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:53:11 INFO  ConnectionUtil:273 - 
2018-10-08 13:55:52 INFO  ConnectionUtil:205 - TestLogin1
2018-10-08 13:55:52 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:55:52 INFO  ConnectionUtil:205 - testlogin2
2018-10-08 13:55:52 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:55:52 INFO  ConnectionUtil:273 - 
2018-10-08 13:56:53 INFO  ConnectionUtil:205 - TestLogin1
2018-10-08 13:56:53 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:56:53 INFO  ConnectionUtil:273 - 
2018-10-08 13:57:31 INFO  ConnectionUtil:205 - TestLogin1
2018-10-08 13:57:31 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:57:31 INFO  ConnectionUtil:205 - testlogin2
2018-10-08 13:57:31 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 13:57:31 INFO  ConnectionUtil:273 - 
2018-10-08 14:00:47 INFO  ConnectionUtil:205 - TestLogin1
2018-10-08 14:00:47 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 14:00:47 INFO  ConnectionUtil:205 - TestLogin1testlogin2
2018-10-08 14:00:47 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 14:00:47 INFO  ConnectionUtil:273 - 
2018-10-08 14:01:11 INFO  ConnectionUtil:205 - TestLogin1
2018-10-08 14:01:11 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 14:01:11 INFO  ConnectionUtil:205 - TestLogin1testlogin2
2018-10-08 14:01:11 INFO  ConnectionUtil:211 - NOT A VALID LOGIN NAME
2018-10-08 14:01:11 INFO  ConnectionUtil:273 - 
2018-10-08 14:02:41 INFO  ConnectionUtil:204 - 
2018-10-08 14:02:41 INFO  ConnectionUtil:210 - NOT A VALID LOGIN NAME
2018-10-08 14:02:41 INFO  ConnectionUtil:204 - 
2018-10-08 14:02:41 INFO  ConnectionUtil:210 - NOT A VALID LOGIN NAME
2018-10-08 14:02:41 INFO  ConnectionUtil:272 - 
2018-10-08 14:03:37 INFO  ConnectionUtil:207 - NOT A VALID LOGIN NAME
2018-10-08 14:03:37 INFO  ConnectionUtil:207 - NOT A VALID LOGIN NAME
2018-10-08 14:03:37 INFO  ConnectionUtil:216 - NOT a valid customer size
2018-10-08 14:03:37 INFO  ConnectionUtil:269 - 
2018-10-08 14:11:49 INFO  ConnectionUtil:257 - 
2018-10-08 14:13:29 INFO  ConnectionUtil:260 - 
2018-10-08 14:15:23 INFO  ConnectionUtil:257 - 
2018-10-08 14:18:53 INFO  ConnectionUtil:259 - [Customer [id=null, firstName=null, lastName=null, loginName=testlogin2, account=null, customerHash=null, emailAddress=null], Customer [id=null, firstName=null, lastName=null, loginName=TestLogin1, account=null, customerHash=null, emailAddress=null]]
2018-10-08 14:20:14 INFO  ConnectionUtil:259 - [Customer [id=null, firstName=null, lastName=null, loginName=testlogin2, account=null, customerHash=null, emailAddress=null], Customer [id=null, firstName=null, lastName=null, loginName=TestLogin1, account=null, customerHash=null, emailAddress=null]]
2018-10-08 14:23:55 INFO  ConnectionUtil:259 - [Customer [id=null, firstName=null, lastName=null, loginName=testlogin2, account=null, customerHash=null, emailAddress=null], Customer [id=null, firstName=null, lastName=null, loginName=TestLogin1, account=null, customerHash=null, emailAddress=null]]
2018-10-08 14:24:26 INFO  ConnectionUtil:259 - [Customer [id=null, firstName=null, lastName=null, loginName=testlogin2, account=null, customerHash=null, emailAddress=null], Customer [id=null, firstName=null, lastName=null, loginName=TestLogin1, account=null, customerHash=null, emailAddress=null]]
2018-10-08 14:26:12 INFO  ConnectionUtil:259 - [Customer [id=null, firstName=null, lastName=null, loginName=testlogin2, account=null, customerHash=null, emailAddress=null], Customer [id=null, firstName=null, lastName=null, loginName=TestLogin1, account=null, customerHash=null, emailAddress=null]]
2018-10-08 14:32:35 INFO  ConnectionUtil:245 - Not a valid login name
2018-10-08 15:08:49 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:08:49 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 15:09:52 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:09:53 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 15:09:53 INFO  Controller:92 - Not a valid login name or password; please try again
2018-10-08 15:10:07 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:10:07 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 15:10:07 INFO  Controller:92 - Not a valid login name or password; please try again
2018-10-08 15:10:26 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:10:26 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 15:10:26 INFO  Controller:92 - Not a valid login name or password; please try again
2018-10-08 15:11:04 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:11:04 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 15:11:04 INFO  Controller:92 - Not a valid login name or password; please try again
2018-10-08 15:16:09 INFO  BankService:102 - false
2018-10-08 15:16:42 INFO  BankService:102 - true
2018-10-08 15:17:07 INFO  BankService:102 - false
2018-10-08 15:18:04 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:18:04 INFO  BankService:102 - false
2018-10-08 15:18:34 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:18:35 INFO  BankService:102 - true
2018-10-08 15:18:44 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:18:45 INFO  BankService:102 - false
2018-10-08 15:19:05 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:19:06 INFO  BankService:102 - true
2018-10-08 15:19:34 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:19:34 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:19:35 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 15:19:35 INFO  Controller:92 - Not a valid login name or password; please try again
2018-10-08 15:19:52 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:19:52 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:19:52 INFO  Controller:96 - In else of inValidSession
2018-10-08 15:20:48 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:20:48 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:20:49 INFO  Controller:96 - In else of inValidSession
2018-10-08 15:24:02 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:24:02 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:24:02 INFO  Controller:96 - In else of inValidSession
2018-10-08 15:48:54 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:48:54 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:48:55 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 15:48:55 INFO  Controller:132 - Not a valid login name or password; please try again
2018-10-08 15:49:32 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:49:32 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:49:33 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 15:49:33 INFO  Controller:132 - Not a valid login name or password; please try again
2018-10-08 15:49:58 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:49:58 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:49:58 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 15:49:58 INFO  Controller:132 - Not a valid login name or password; please try again
2018-10-08 15:50:06 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:50:06 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:50:06 INFO  Controller:136 - In else of inValidSession
2018-10-08 15:56:05 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:56:05 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:56:06 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 15:56:06 INFO  Controller:133 - Not a valid login name or password; please try again
2018-10-08 15:56:13 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:56:13 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:56:13 INFO  Controller:137 - In else of inValidSession
2018-10-08 15:58:25 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:58:25 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:58:26 INFO  Controller:130 - In else of inValidSession
2018-10-08 15:59:58 INFO  BankService:86 - In bankHasLoginName
2018-10-08 15:59:58 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 15:59:58 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 15:59:58 INFO  Controller:126 - Not a valid login name or password; please try again
2018-10-08 16:00:39 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:00:39 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:00:40 INFO  Controller:130 - In else of inValidSession
2018-10-08 16:01:01 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:01:01 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:01:01 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 16:02:07 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:02:07 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:02:07 INFO  ConnectionUtil:231 - INVALID
2018-10-08 16:02:07 INFO  ConnectionUtil:231 - INVALID
2018-10-08 16:02:07 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 16:02:15 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:02:15 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:02:15 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:02:15 INFO  Controller:130 - In else of inValidSession
2018-10-08 16:03:41 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:03:41 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:03:42 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:03:42 INFO  Controller:130 - In else of inValidSession
2018-10-08 16:03:59 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:03:59 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:03:59 INFO  ConnectionUtil:231 - INVALID
2018-10-08 16:03:59 INFO  ConnectionUtil:231 - INVALID
2018-10-08 16:03:59 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 16:04:36 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:04:36 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:04:36 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:04:36 INFO  Controller:130 - In else of inValidSession
2018-10-08 16:04:56 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:04:56 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:04:56 INFO  ConnectionUtil:231 - INVALID
2018-10-08 16:04:56 INFO  ConnectionUtil:231 - INVALID
2018-10-08 16:04:56 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 16:05:00 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:05:00 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:05:00 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:05:00 INFO  Controller:130 - In else of inValidSession
2018-10-08 16:05:17 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:05:17 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:05:17 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:05:17 INFO  Controller:130 - In else of inValidSession
2018-10-08 16:05:39 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:05:39 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:05:40 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:05:40 INFO  Controller:130 - In else of inValidSession
2018-10-08 16:06:37 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:06:37 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:06:38 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:06:38 INFO  Controller:130 - In else of inValidSession
2018-10-08 16:07:13 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:07:13 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:07:14 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:07:14 INFO  Controller:130 - In else of inValidSession
2018-10-08 16:07:27 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:07:27 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:07:28 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:07:28 INFO  Controller:130 - In else of inValidSession
2018-10-08 16:08:29 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:08:29 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:08:30 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:08:30 INFO  Controller:130 - In else of inValidSession
2018-10-08 16:09:40 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:09:40 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:09:41 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:09:41 INFO  Controller:130 - In else of inValidSession
2018-10-08 16:11:33 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:11:33 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:11:33 INFO  ConnectionUtil:231 - INVALID
2018-10-08 16:11:33 INFO  ConnectionUtil:231 - INVALID
2018-10-08 16:11:33 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 16:11:42 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:11:42 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:11:42 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:11:42 INFO  Controller:127 - In else of inValidSession
2018-10-08 16:24:19 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:24:20 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:24:20 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:24:20 INFO  Controller:126 - In else of inValidSession
2018-10-08 16:25:10 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:25:10 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:25:11 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:25:11 INFO  Controller:126 - In else of inValidSession
2018-10-08 16:26:26 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:26:26 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:26:26 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:26:26 INFO  Controller:126 - In else of inValidSession
2018-10-08 16:32:12 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:32:12 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:32:13 INFO  ConnectionUtil:231 - INVALID
2018-10-08 16:32:13 INFO  ConnectionUtil:231 - INVALID
2018-10-08 16:32:13 INFO  BankService:90 - Not a valid login name... throwing exception....
2018-10-08 16:32:23 INFO  BankService:86 - In bankHasLoginName
2018-10-08 16:32:23 INFO  ConnectionUtil:221 - In isValidLoginName
2018-10-08 16:32:23 INFO  ConnectionUtil:227 - VALID
2018-10-08 16:32:23 INFO  Controller:126 - In else of inValidSession
2018-10-08 22:24:26 ERROR ConnectionUtil:184 - Couldn't retrieve balance
java.sql.SQLException: Invalid column name
	at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3965)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.findColumn(InsensitiveScrollableResultSet.java:299)
	at oracle.jdbc.driver.GeneratedResultSet.getDouble(GeneratedResultSet.java:1328)
	at com.revature.repository.BankRepositoryJdbc.findBalanceByCustomerId(BankRepositoryJdbc.java:178)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:255)
2018-10-08 22:24:26 INFO  ConnectionUtil:255 - 0.0
2018-10-08 22:25:01 ERROR ConnectionUtil:184 - Couldn't retrieve balance
java.sql.SQLException: Invalid column name
	at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3965)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.findColumn(InsensitiveScrollableResultSet.java:299)
	at oracle.jdbc.driver.GeneratedResultSet.getDouble(GeneratedResultSet.java:1328)
	at com.revature.repository.BankRepositoryJdbc.findBalanceByCustomerId(BankRepositoryJdbc.java:178)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:255)
2018-10-08 22:25:01 INFO  ConnectionUtil:255 - 0.0
2018-10-08 22:25:23 ERROR ConnectionUtil:184 - Couldn't retrieve balance
java.sql.SQLException: Invalid column name
	at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3965)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.findColumn(InsensitiveScrollableResultSet.java:299)
	at oracle.jdbc.driver.GeneratedResultSet.getDouble(GeneratedResultSet.java:1328)
	at com.revature.repository.BankRepositoryJdbc.findBalanceByCustomerId(BankRepositoryJdbc.java:178)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:255)
2018-10-08 22:25:23 INFO  ConnectionUtil:255 - 0.0
2018-10-08 22:26:12 ERROR ConnectionUtil:184 - Couldn't retrieve balance
java.sql.SQLSyntaxErrorException: ORA-00904: "SUM": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:776)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:897)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1034)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3867)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1502)
	at com.revature.repository.BankRepositoryJdbc.findBalanceByCustomerId(BankRepositoryJdbc.java:173)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:255)
2018-10-08 22:26:12 INFO  ConnectionUtil:255 - 0.0
2018-10-08 22:27:13 INFO  ConnectionUtil:255 - 600.0
2018-10-08 22:28:17 INFO  ConnectionUtil:256 - 600.0
2018-10-08 22:36:16 INFO  BankService:81 - In bankHasLoginName
2018-10-08 22:36:16 INFO  ConnectionUtil:227 - In isValidLoginName
2018-10-08 22:36:17 INFO  ConnectionUtil:237 - INVALID
2018-10-08 22:36:17 INFO  ConnectionUtil:233 - VALID
2018-10-08 22:36:17 INFO  Controller:124 - In else of inValidSession
2018-10-08 22:36:20 INFO  BankService:93 - In getAccountBalance
2018-10-08 22:53:27 INFO  BankService:81 - In bankHasLoginName
2018-10-08 22:53:27 INFO  ConnectionUtil:227 - In isValidLoginName
2018-10-08 22:53:28 INFO  ConnectionUtil:233 - VALID
2018-10-08 22:53:28 INFO  Controller:124 - In else of inValidSession
2018-10-08 22:53:30 INFO  BankService:93 - In getAccountBalance
2018-10-08 22:59:13 INFO  BankService:81 - In bankHasLoginName
2018-10-08 22:59:13 INFO  ConnectionUtil:227 - In isValidLoginName
2018-10-08 22:59:14 INFO  ConnectionUtil:233 - VALID
2018-10-08 22:59:14 INFO  Controller:128 - In else of inValidSession
2018-10-08 22:59:16 INFO  BankService:93 - In getAccountBalance
2018-10-08 23:00:04 INFO  BankService:81 - In bankHasLoginName
2018-10-08 23:00:04 INFO  ConnectionUtil:227 - In isValidLoginName
2018-10-08 23:00:05 INFO  ConnectionUtil:233 - VALID
2018-10-08 23:00:05 INFO  Controller:128 - In else of inValidSession
2018-10-08 23:00:08 INFO  BankService:93 - In getAccountBalance
2018-10-08 23:00:51 INFO  BankService:81 - In bankHasLoginName
2018-10-08 23:00:51 INFO  ConnectionUtil:227 - In isValidLoginName
2018-10-08 23:00:52 INFO  ConnectionUtil:233 - VALID
2018-10-08 23:00:52 INFO  Controller:128 - In else of inValidSession
2018-10-08 23:00:52 INFO  BankService:93 - In getAccountBalance
2018-10-08 23:05:32 INFO  BankService:81 - In bankHasLoginName
2018-10-08 23:05:32 INFO  ConnectionUtil:227 - In isValidLoginName
2018-10-08 23:05:33 INFO  ConnectionUtil:233 - VALID
2018-10-08 23:05:33 INFO  Controller:128 - In else of inValidSession
2018-10-08 23:05:33 INFO  BankService:93 - In getAccountBalance
2018-10-08 23:29:50 INFO  BankService:53 - In register Customer
2018-10-08 23:29:50 INFO  ConnectionUtil:102 - In bank repository
2018-10-08 23:29:51 ERROR ConnectionUtil:124 - Couldn't insert customer
java.sql.SQLSyntaxErrorException: ORA-00947: not enough values

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:118)
	at com.revature.service.BankServiceImpl.registerCustomer(BankServiceImpl.java:54)
	at com.revature.test.AccountRegistrationTest.registrationSuccessCustomer(AccountRegistrationTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 23:37:12 INFO  BankService:53 - In register Customer
2018-10-08 23:37:12 INFO  ConnectionUtil:102 - In bank repository
2018-10-08 23:37:13 INFO  ConnectionUtil:119 - statement.executeUpdate > 0
2018-10-08 23:38:32 INFO  BankService:24 - In register Account
2018-10-08 23:38:33 ERROR ConnectionUtil:44 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-02291: integrity constraint (BANK_DB.FK_CUSTOMER_ACCOUNT) violated - parent key not found

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:39)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:25)
	at com.revature.test.AccountRegistrationTest.registrationSuccessAccount(AccountRegistrationTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 23:40:36 INFO  BankService:24 - In register Account
2018-10-08 23:40:37 ERROR ConnectionUtil:44 - Couldn't insert account
java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("BANK_DB"."ACCOUNT"."A_ACCOUNT_TYPE")

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:39)
	at com.revature.service.BankServiceImpl.registerAccount(BankServiceImpl.java:25)
	at com.revature.test.AccountRegistrationTest.registrationFailure(AccountRegistrationTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 23:40:37 INFO  BankService:53 - In register Customer
2018-10-08 23:40:37 INFO  ConnectionUtil:102 - In bank repository
2018-10-08 23:40:37 ERROR ConnectionUtil:124 - Couldn't insert customer
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (BANK_DB.UNIQUE_LOGIN) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:118)
	at com.revature.service.BankServiceImpl.registerCustomer(BankServiceImpl.java:54)
	at com.revature.test.AccountRegistrationTest.registrationSuccessCustomer(AccountRegistrationTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 23:40:37 INFO  BankService:24 - In register Account
2018-10-08 23:41:56 INFO  BankService:53 - In register Customer
2018-10-08 23:41:56 INFO  ConnectionUtil:102 - In bank repository
2018-10-08 23:41:57 ERROR ConnectionUtil:124 - Couldn't insert customer
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (BANK_DB.UNIQUE_LOGIN) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.BankRepositoryJdbc.insert(BankRepositoryJdbc.java:118)
	at com.revature.service.BankServiceImpl.registerCustomer(BankServiceImpl.java:54)
	at com.revature.test.AccountRegistrationTest.registrationSuccessCustomer(AccountRegistrationTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-10-08 23:41:57 INFO  BankService:24 - In register Account
2018-10-08 23:42:48 INFO  BankService:24 - In register Account
2018-10-09 06:55:53 ERROR ConnectionUtil:213 - Couldn't retrieve balance
java.sql.SQLSyntaxErrorException: ORA-00904: "CUSTOMER"."TESTLOGIN1": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:776)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:897)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1034)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3867)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1502)
	at com.revature.repository.BankRepositoryJdbc.findBalanceByLoginName(BankRepositoryJdbc.java:201)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:285)
2018-10-09 06:55:53 INFO  ConnectionUtil:285 - 0.0
2018-10-09 06:56:43 ERROR ConnectionUtil:213 - Couldn't retrieve balance
java.sql.SQLSyntaxErrorException: ORA-00904: "CUSTOMER"."TESTLOGIN2": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:776)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:897)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1034)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3867)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1502)
	at com.revature.repository.BankRepositoryJdbc.findBalanceByLoginName(BankRepositoryJdbc.java:201)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:285)
2018-10-09 06:56:43 INFO  ConnectionUtil:285 - 0.0
2018-10-09 07:04:20 INFO  ConnectionUtil:191 - In findBalanceByLogingName
2018-10-09 07:04:20 ERROR ConnectionUtil:208 - Couldn't retrieve balance
java.sql.SQLSyntaxErrorException: ORA-00904: "TESTLOGIN2": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:776)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:897)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1034)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3867)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1502)
	at com.revature.repository.BankRepositoryJdbc.findBalanceByLoginName(BankRepositoryJdbc.java:196)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:280)
2018-10-09 07:04:20 INFO  ConnectionUtil:280 - 0.0
2018-10-09 07:11:11 INFO  ConnectionUtil:191 - In findBalanceByLogingName
2018-10-09 07:11:11 ERROR ConnectionUtil:213 - Couldn't retrieve balance
java.sql.SQLSyntaxErrorException: ORA-00904: "TESTLOGIN2": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:776)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:897)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1034)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3867)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1502)
	at com.revature.repository.BankRepositoryJdbc.findBalanceByLoginName(BankRepositoryJdbc.java:201)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:285)
2018-10-09 07:11:11 INFO  ConnectionUtil:285 - 0.0
2018-10-09 07:12:14 INFO  ConnectionUtil:191 - In findBalanceByLogingName
2018-10-09 07:12:14 ERROR ConnectionUtil:213 - Couldn't retrieve balance
java.sql.SQLSyntaxErrorException: ORA-00904: "TESTLOGIN2": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:776)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:897)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1034)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3867)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1502)
	at com.revature.repository.BankRepositoryJdbc.findBalanceByLoginName(BankRepositoryJdbc.java:201)
	at com.revature.repository.BankRepositoryJdbc.main(BankRepositoryJdbc.java:285)
2018-10-09 07:12:14 INFO  ConnectionUtil:285 - 0.0
2018-10-09 07:17:44 INFO  ConnectionUtil:193 - In findBalanceByLogingName
2018-10-09 07:17:44 INFO  ConnectionUtil:289 - 0.0
2018-10-09 07:18:05 INFO  ConnectionUtil:193 - In findBalanceByLogingName
2018-10-09 07:18:05 INFO  ConnectionUtil:289 - 4075.0
2018-10-09 07:23:47 INFO  ConnectionUtil:193 - In findBalanceByLogingName
2018-10-09 07:23:47 INFO  BankService:111 - 4075.0
2018-10-09 07:25:03 INFO  BankService:81 - In bankHasLoginName
2018-10-09 07:25:03 INFO  ConnectionUtil:259 - In isValidLoginName
2018-10-09 07:25:04 INFO  ConnectionUtil:269 - INVALID
2018-10-09 07:25:04 INFO  ConnectionUtil:265 - VALID
2018-10-09 07:25:04 INFO  Controller:110 - In else of inValidSession
2018-10-09 07:25:08 INFO  BankService:100 - In getAccountBalanceByLogin
2018-10-09 07:25:08 INFO  ConnectionUtil:193 - In findBalanceByLogingName
2018-10-09 07:25:08 INFO  Controller:148 - 4075.0
